/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bdcc.kafkastreams.entities;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExpediaCategorized extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3563793201206806856L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExpediaCategorized\",\"namespace\":\"com.bdcc.kafkastreams.entities\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"hotel_id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"category\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExpediaCategorized> ENCODER =
      new BinaryMessageEncoder<ExpediaCategorized>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExpediaCategorized> DECODER =
      new BinaryMessageDecoder<ExpediaCategorized>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ExpediaCategorized> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ExpediaCategorized> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ExpediaCategorized>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ExpediaCategorized to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ExpediaCategorized from a ByteBuffer. */
  public static ExpediaCategorized fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Long id;
  @Deprecated public java.lang.Long hotel_id;
  @Deprecated public java.lang.CharSequence category;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExpediaCategorized() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param hotel_id The new value for hotel_id
   * @param category The new value for category
   */
  public ExpediaCategorized(java.lang.Long id, java.lang.Long hotel_id, java.lang.CharSequence category) {
    this.id = id;
    this.hotel_id = hotel_id;
    this.category = category;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return hotel_id;
    case 2: return category;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: hotel_id = (java.lang.Long)value$; break;
    case 2: category = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'hotel_id' field.
   * @return The value of the 'hotel_id' field.
   */
  public java.lang.Long getHotelId() {
    return hotel_id;
  }

  /**
   * Sets the value of the 'hotel_id' field.
   * @param value the value to set.
   */
  public void setHotelId(java.lang.Long value) {
    this.hotel_id = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.CharSequence getCategory() {
    return category;
  }

  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.CharSequence value) {
    this.category = value;
  }

  /**
   * Creates a new ExpediaCategorized RecordBuilder.
   * @return A new ExpediaCategorized RecordBuilder
   */
  public static com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder newBuilder() {
    return new com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder();
  }

  /**
   * Creates a new ExpediaCategorized RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExpediaCategorized RecordBuilder
   */
  public static com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder newBuilder(com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder other) {
    return new com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder(other);
  }

  /**
   * Creates a new ExpediaCategorized RecordBuilder by copying an existing ExpediaCategorized instance.
   * @param other The existing instance to copy.
   * @return A new ExpediaCategorized RecordBuilder
   */
  public static com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder newBuilder(com.bdcc.kafkastreams.entities.ExpediaCategorized other) {
    return new com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder(other);
  }

  /**
   * RecordBuilder for ExpediaCategorized instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExpediaCategorized>
    implements org.apache.avro.data.RecordBuilder<ExpediaCategorized> {

    private java.lang.Long id;
    private java.lang.Long hotel_id;
    private java.lang.CharSequence category;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hotel_id)) {
        this.hotel_id = data().deepCopy(fields()[1].schema(), other.hotel_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ExpediaCategorized instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bdcc.kafkastreams.entities.ExpediaCategorized other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.hotel_id)) {
        this.hotel_id = data().deepCopy(fields()[1].schema(), other.hotel_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.category)) {
        this.category = data().deepCopy(fields()[2].schema(), other.category);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'hotel_id' field.
      * @return The value.
      */
    public java.lang.Long getHotelId() {
      return hotel_id;
    }

    /**
      * Sets the value of the 'hotel_id' field.
      * @param value The value of 'hotel_id'.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder setHotelId(java.lang.Long value) {
      validate(fields()[1], value);
      this.hotel_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'hotel_id' field has been set.
      * @return True if the 'hotel_id' field has been set, false otherwise.
      */
    public boolean hasHotelId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'hotel_id' field.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder clearHotelId() {
      hotel_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategory() {
      return category;
    }

    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder setCategory(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.category = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public com.bdcc.kafkastreams.entities.ExpediaCategorized.Builder clearCategory() {
      category = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExpediaCategorized build() {
      try {
        ExpediaCategorized record = new ExpediaCategorized();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.hotel_id = fieldSetFlags()[1] ? this.hotel_id : (java.lang.Long) defaultValue(fields()[1]);
        record.category = fieldSetFlags()[2] ? this.category : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExpediaCategorized>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExpediaCategorized>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExpediaCategorized>
    READER$ = (org.apache.avro.io.DatumReader<ExpediaCategorized>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
